version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Maps localhost:8000 to the container
    volumes:
      - .:/app  # Mounts the current directory into the container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload